version: '3.9'

services:
  mysql:
    image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/mysql:${MYSQL_IMAGE_TAG:-latest}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nestbasepass
      MYSQL_USER: nest-timer
      MYSQL_PASSWORD: nestbasepass
      MYSQL_DATABASE: nestjs_db
    ports:
      - '3309:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql:ro # 挂载初始化脚本
    networks:
      - net-backend
    healthcheck: # 添加健康检查
      test: [CMD, mysqladmin, ping, -uroot, -p$$MYSQL_ROOT_PASSWORD]
      interval: 5s
      timeout: 10s
      retries: 10

  nats:
    image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/nats:${NATS_IMAGE_TAG:-latest}
    container_name: nats
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: [-c, /etc/nats/nats.conf]
    ports:
      - '4222:4222'
      - '8222:8222' # 仅暴露监控端口（集群端口无需暴露）
    networks:
      - net-backend

  redis:
    image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/redis:${REDIS_IMAGE_TAG:-latest}
    container_name: redis
    command: redis-server --requirepass nestbasepass
    ports:
      - '6389:6379'
    networks:
      - net-backend

  nestjs:
    image: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - 3000:3000
      - 3001:3001
      - 3004:3004
      - 3005:3005
      - 3006:3006
      - 3100:3100
    depends_on:
      mysql:
        condition: service_healthy # 依赖健康状态
      redis:
        condition: service_started
      nats:
        condition: service_started
    networks:
      - net-backend

volumes:
  mysql_data:

networks:
  net-backend:
    driver: bridge
