version: '3.9'

services:
  # MySQL 服务
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yujiezhang187332
      MYSQL_USER: nest-timer
      MYSQL_PASSWORD: yujiezhang187332
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis 服务
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass yujiezhang187332
    ports:
      - "6379:6379"

  # MongoDB 服务
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: nest-timer
      MONGO_INITDB_ROOT_PASSWORD: yujiezhang187332
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # NestJS 应用服务
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yujiezhang187332
      MONGO_URI: mongodb://nest-timer:yujiezhang187332@mongo:27017/nestjs_db
      REDIS_DB: 0
      JWT_SECRET: jwtsecret
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_SECRET: myrefreshsecret
      DB_PORT: 3306
      DB_HOST: localhost
      DB_USERNAME: nest-timer
      DB_PASSWORD: yujiezhang187332
      DB_DATABASE: nestjs_db

      EMAIL_HOST: smtp.163.com
      EMAIL_PORT: 465
      EMAIL_USER: 19939926438@163.com
      EMAIL_PASSWORD: KZzjT7VQgmRYrFJ
      EMAIL_FROM: "My Name <myemail@example.com>"

      NATS_SERVER_URL: nats://localhost:4222
      NATS_AUTH_USER: nat_user
      NATS_AUTH_PASSWORD: nat_passwordS

      AUTH_PUBLIC_KEY: dev_AUTH_PUBLIC_KEY
      IS_LOG_EVERY_REQ: Y

      ALI_DEEPDEEK_APP_KEY: sk-1ff471c57bd34a9ca7ba46ea72731479
      ALI_DEEPSEEK_APP_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1

      DEEP_SEEK_APP_KEY: sk-7886de6009b54b7cb2d7662637d98e3e
      DEEP_SEEK_APP_BASE_URL: https://api.deepseek.com
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3005:3005"
      - "3004:3004"
      - "3100:3100"
      - "3006:3006"
    depends_on:
      - mysql
      - redis
      - mongo

volumes:
  mysql_data:
  mongodb_data:
